[package]
name = "dom-basic-example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nestix = { git = "https://github.com/wirelesseye/nestix.git" }
nestix-native = { path = "../../nestix-native", default-features = false, features = ["dom"] }
wasm-bindgen = "0.2.105"
